type Columns =
  'name' |
  'playtime_mean' |
  'playtime_median' |
  'playtime_sd' |
  'playtime_sd_pct' |
  'playtime_rsd' |
  'playtime_rsd_pct' |
  'playtime_mean_ftb' |
  'playtime_mean_ftb_pct' |
  'playtime_median_ftb' |
  'playtime_median_ftb_pct' |
  'steam_game_id' |
  'tags' |
  'oculus_game_id' |
  'steam_price' |
  'steam_price_regular' |
  'steam_price_discount' |
  'oculus_price' |
  'oculus_price_regular' |
  'oculus_price_discount' |
  'lowest_price' |
  'ratings_count' |
  'ratings_count_pct' |
  'positive_ratings_count' |
  'negative_ratings_count' |
  'ratings_ratio' |
  'ratings_ratio_pct' |
  'released_at' |
  'players' |
  'controllers' |
  'vr_modes' |
  'vr_platforms' |
  'gamepad' |
  'vr_only' |
  'platforms' |
  'sysreq_gpu_string' |
  'sysreq_gpu_tokens' |
  'sysreq_index' |
  'sysreq_index_pct' |
  'images' |
  'videos' |
  'thumbnail' |
  'stores' |
  'ratings_pct' |
  'best_discount' |
  'urls' |
  'prices';

export default Columns;
